import type { ExploreResult } from "@/components/explore/explore-types"
import { CATEGORY_OPTIONS } from "@/components/categories/category-taxonomy"

export const EXPLORE_CITY_OPTIONS = ["Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur"]

export const EXPLORE_CATEGORY_OPTIONS = [
  { value: "all", label: "All categories" },
  ...CATEGORY_OPTIONS,
]

export const EXPLORE_PRICE_OPTIONS = [
  { value: "any", label: "Any price" },
  { value: "$", label: "$ Budget" },
  { value: "$$", label: "$$ Mid-range" },
  { value: "$$$", label: "$$$ Treat night" },
]

export const EXPLORE_SORT_OPTIONS = [
  { value: "recommended", label: "Recommended" },
  { value: "top-rated", label: "Top rated" },
  { value: "most-reviewed", label: "Most reviewed" },
  { value: "nearest", label: "Nearest" },
]

export const EXPLORE_RESULTS: ExploreResult[] = [
  {
    id: "thakali-kitchen",
    slug: "thakali-kitchen",
    name: "Thakali Kitchen",
    imageUrl: "/nepali-restaurant-thakali-food.jpg",
    cuisine: "Nepali • Traditional",
    category: "restaurants",
    rating: 4.8,
    reviewCount: 324,
    location: "Thamel, Kathmandu",
    city: "Kathmandu",
    openNow: true,
    priceRange: "$$",
    distanceKm: 1.2,
    standoutDish: "Thakali khana set",
    trustNote: "Dependable achar, generous refills, and the kind of plate that works for a hungry group.",
    whyGo: "Worth the walk when you want something filling, familiar, and actually consistent.",
    featured: true,
    editorialTakeaway: "One of the safer category anchors when a group wants a proper meal and no one wants surprises.",
    bestFor: "Family dinner and dependable full meals",
  },
  {
    id: "momo-central",
    slug: "momo-central",
    name: "Momo Central",
    imageUrl: "/nepali-momo-dumplings-restaurant.jpg",
    cuisine: "Nepali • Dumplings",
    category: "street-food",
    rating: 4.7,
    reviewCount: 512,
    location: "New Road, Kathmandu",
    city: "Kathmandu",
    openNow: true,
    priceRange: "$",
    distanceKm: 0.9,
    standoutDish: "Buff jhol momo",
    trustNote: "The broth has real depth, the spice lands well, and it still moves fast even when crowded.",
    whyGo: "A dependable late-evening call when the group wants momos and no one wants to overthink it.",
    featured: true,
    editorialTakeaway: "A strong first look when the craving is specific and the decision needs to be quick.",
    bestFor: "Late-evening momo cravings",
  },
  {
    id: "newari-bhoj",
    slug: "newari-bhoj",
    name: "Newari Bhoj",
    imageUrl: "/newari-traditional-food-nepal.jpg",
    cuisine: "Newari • Traditional",
    category: "local-cuisine",
    rating: 4.9,
    reviewCount: 278,
    location: "Bhaktapur Durbar Area",
    city: "Bhaktapur",
    openNow: false,
    priceRange: "$$",
    distanceKm: 5.3,
    standoutDish: "Choila platter",
    trustNote: "Real smoke, real chili heat, and enough neighborhood character to feel like more than just a stop.",
    whyGo: "Worth the ride if the point of the meal is flavor and local feel, not just convenience.",
    featured: true,
    editorialTakeaway: "A more rooted local-cuisine pick when flavor and place matter more than convenience.",
    bestFor: "Visitors and locals chasing stronger regional flavor",
  },
  {
    id: "lakeside-cafe",
    slug: "lakeside-cafe",
    name: "Lakeside Cafe",
    imageUrl: "/lakeside-cafe-pokhara-nepal.jpg",
    cuisine: "Cafe • Continental",
    category: "cafes",
    rating: 4.6,
    reviewCount: 189,
    location: "Lakeside, Pokhara",
    city: "Pokhara",
    openNow: true,
    priceRange: "$$",
    distanceKm: 1.4,
    standoutDish: "Cold brew and mushroom toast",
    trustNote: "A calmer cafe pick when the setting matters, but the food still has to justify the stop.",
    whyGo: "Good for a slower afternoon or a meeting that should still end in something worth eating.",
    featured: true,
    editorialTakeaway: "Useful when you want a cafe that feels intentional instead of just available.",
    bestFor: "Slow afternoons and coffee meetings",
  },
  {
    id: "sekuwa-corner",
    slug: "sekuwa-corner",
    name: "Sekuwa Corner",
    imageUrl: "/nepali-sekuwa-bbq-grilled-meat.jpg",
    cuisine: "Nepali • BBQ",
    category: "street-food",
    rating: 4.5,
    reviewCount: 156,
    location: "Patan, Lalitpur",
    city: "Lalitpur",
    openNow: true,
    priceRange: "$",
    distanceKm: 1.1,
    standoutDish: "Buff sekuwa",
    trustNote: "Smoky enough to be memorable, with achar that keeps the plate from feeling one-note.",
    whyGo: "A strong quick dinner pick when you want grilled food that still feels local.",
    editorialTakeaway: "Better for people who want street food with a little more fire and focus than snack-chain comfort.",
    bestFor: "Quick grilled dinners",
  },
  {
    id: "sel-roti-house",
    slug: "sel-roti-house",
    name: "Sel Roti House",
    imageUrl: "/nepali-sel-roti-street-food.jpg",
    cuisine: "Street Food • Nepali",
    category: "street-food",
    rating: 4.6,
    reviewCount: 144,
    location: "Patan Dhoka, Lalitpur",
    city: "Lalitpur",
    openNow: true,
    priceRange: "$",
    distanceKm: 0.8,
    standoutDish: "Sel roti with aalu tama",
    trustNote: "Comforting, reasonably priced, and useful when you want something local instead of another snack-chain decision.",
    whyGo: "A better-than-average short detour when you want fast food that still has identity.",
    featured: true,
    editorialTakeaway: "One of the easier ways into something local when you want comfort without a full sit-down meal.",
    bestFor: "Fast local comfort food",
  },
  {
    id: "himalayan-java-jhamsikhel",
    slug: "himalayan-java-jhamsikhel",
    name: "Himalayan Java",
    imageUrl: "/himalayan-java-coffee-cafe-nepal.jpg",
    cuisine: "Cafe • Coffee",
    category: "cafes",
    rating: 4.4,
    reviewCount: 410,
    location: "Jhamsikhel, Lalitpur",
    city: "Lalitpur",
    openNow: true,
    priceRange: "$$",
    distanceKm: 1.7,
    standoutDish: "Mocha and breakfast plate",
    trustNote: "Reliable when the group wants coffee, Wi-Fi, and a low-risk place to sit for a while.",
    whyGo: "Not the most surprising pick, but often the easiest useful one.",
    editorialTakeaway: "A dependable fallback when the plan is more about sitting well than chasing novelty.",
    bestFor: "Meetings, coffee, and longer sits",
  },
  {
    id: "bhojan-griha",
    slug: "bhojan-griha",
    name: "Bhojan Griha",
    imageUrl: "/nepali-restaurant-traditional-interior.jpg",
    cuisine: "Nepali • Heritage Dining",
    category: "fine-dining",
    rating: 4.7,
    reviewCount: 205,
    location: "Dillibazar, Kathmandu",
    city: "Kathmandu",
    openNow: false,
    priceRange: "$$$",
    distanceKm: 2.6,
    standoutDish: "Traditional thali experience",
    trustNote: "Best when you want atmosphere and a full evening, not just a plate and a quick exit.",
    whyGo: "Worth the ride for visitors, family dinners, or when the setting needs to carry some weight.",
    featured: true,
    editorialTakeaway: "A stronger category pick for nights when the room matters almost as much as the food.",
    bestFor: "Dates, family occasions, and guests",
  },
]
